[project]
name = "tarkov-guns"
version = "0.1.0"
description = "Tarkov Weapon Mod Optimizer"
authors = ["Ahai"]

[dependencies]
python = ">=3.10"
requests = ">=2.31.0"
streamlit = ">=1.30.0"
plotly = ">=5.18.0"
pandas = ">=2.0.0"
altair = ">=5.0.0"

[tasks]
start = "streamlit run app.py"

[pypi-dependencies]
ortools = ">=9.0.0"
